### ISSUE TITLE
Add support for delta time patch

### ISSUE THREAD

**Issue by Whatcookie** [gibbed/DemonsSoulsDebug#4]
delta time patch can be found here: https://wiki.rpcs3.net/index.php?title=Help:Game_Patches#Demon.27s_Souls

**Comment by poli-san** [comment]
Hi. I am trying to make your code compatible with Japanese version 1.04. But there are places where I have no idea because of my poor skills. It is "jump to code cave". How do I scan with a cheat engine?
PPU-68544b29e92609ccb2710f485ae7708e4cb35df1: #BCJS30022 1.04
#Set 60FPS with no frameskip
#by Gibbed
   - [be16, 0x240D0, 0x981f ] 

#delta time
#by Whatcookie
##############################################################
   - [ be32, ,  ] # jump to code cave  <- help me ><

#get mftb
   - [ be32, 0x016C8AA0, 0x7eac42e6 ] # mftb r21              // Move from timebase register (clock)

#get mftb delta
   - [ be32, 0x016C8AA4, 0x3ec00185 ] # lis r22,0x0185        // load high bits of address
   - [ be32, 0x016C8AA8, 0x3ad62608 ] # addi r22,r22,0x2608   // load low bits of address
   - [ be32, 0x016C8AAC, 0x7e96a02a ] # ldx r20,r22,r20       // load previous frames mftb reading
   - [ be32, 0x016C8AB0, 0xfab60000 ] # std r21,0x0(r22)      // store this frames mftb reading
   - [ be32, 0x016C8AB4, 0x7e74a850 ] # subf r19,r21,r20      // subtract previous mftb reading from this mftb frames reading

#mftb delta to float
   - [ be32, 0x016C8AB8, 0xfa760018 ] # std r19,0x18(r22)     // store mftb delta (to be loaded into FPR)
   - [ be32, 0x016C8ABC, 0xcbd60018 ] # lfd f30,0x18(r22)     // load mftb delta into FPR
   - [ be32, 0x016C8AC0, 0xffc0f69c ] # fcfid f30,f30         // convert integer to double
   - [ be32, 0x016C8AC4, 0xffc0f018 ] # frsp f30,f30          // round to single precision

#mftb delta to seconds
   - [ be32, 0x016C8AC8, 0x3e40016c ] # r18,0x16c             // load high bits constants pointer
   - [ be32, 0x016C8ACC, 0x3a527c30 ] # addi r18,r18,0x7c30   // load low bits of constants pointer
   - [ be32, 0x016C8AD0, 0xc3b20054 ] # lfs f29,0x54(r18)     // load timebase frequency constant
   - [ be32, 0x016C8AD4, 0xc3920058 ] # lfs f28,0x58(r18)     // load maximum timestep size
   - [ be32, 0x016C8AD8, 0xfffee824 ] # fdiv f31,f30,f29      // divide timebase delta by timebase frequency

#check timestep size
   - [ be32, 0x016C8ADC, 0xff9fe000 ] # fcmpu cr7,f31,f28     // compare current delta time to maximum timestep
   - [ be32, 0x016C8AE0, 0x419c0008 ] # blt +0x08             // don't return the maximum timestep size

#set maximum timestep
   - [ be32, 0x016C8AE4, 0xffe0e090 ] # fmr f31,f28           // move maximum timestep to be returned

#cleanup
   - [ be32, 0x016C8AE8, 0x7e94a278 ] # xor r20,r20,r20       // zero r20
   - [ be32, 0x016C8AEC, 0x7e94a278 ] # xor r19,r19,r19       // zero r19
   - [ be32, 0x016C8AF0, 0x4e800020 ] # blr                   // return

#constants
   - [ be32, 0x016C8AF4, 0x4c989680 ]  # timebase frequency as hexfloat (80mhz)
   - [ bef32, 0x016C8AF8, 0.05000000 ] # maximum timestep size (50ms or 20fps)
##############################################################

**Comment by Whatcookie** [comment]
It's not so simple to explain, I may port it later, or perhaps gibbed will be able to sometime later.

**Comment by poli-san** [comment]
thank you, sir!
